// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe2VDjkze_yEvho31p76j_cbiRgKUIYeg',
    appId: '1:259206374027:web:de1af2214bb63bf5c76a8e',
    messagingSenderId: '259206374027',
    projectId: 'o-nepali',
    authDomain: 'o-nepali.firebaseapp.com',
    databaseURL: 'https://o-nepali-default-rtdb.firebaseio.com',
    storageBucket: 'o-nepali.firebasestorage.app',
    measurementId: 'G-4EJMKLEGEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS3R2yPanym3CbkJ5hsf2nNJkVQXs6SaQ',
    appId: '1:259206374027:android:3170dedbd021f4fdc76a8e',
    messagingSenderId: '259206374027',
    projectId: 'o-nepali',
    databaseURL: 'https://o-nepali-default-rtdb.firebaseio.com',
    storageBucket: 'o-nepali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSVkqoFWbp54TaiztHepNoLLoLiNTCYlc',
    appId: '1:259206374027:ios:80fac7c7deff46b4c76a8e',
    messagingSenderId: '259206374027',
    projectId: 'o-nepali',
    databaseURL: 'https://o-nepali-default-rtdb.firebaseio.com',
    storageBucket: 'o-nepali.firebasestorage.app',
    androidClientId:
        '259206374027-8s7mtkn4crb15au6177juljdmdt5frma.apps.googleusercontent.com',
    iosClientId:
        '259206374027-krn41ok7sioklh1obf5q45u2bkosroao.apps.googleusercontent.com',
    iosBundleId: 'fun.onepali.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSVkqoFWbp54TaiztHepNoLLoLiNTCYlc',
    appId: '1:259206374027:ios:eece64b49f4a9e9dc76a8e',
    messagingSenderId: '259206374027',
    projectId: 'o-nepali',
    databaseURL: 'https://o-nepali-default-rtdb.firebaseio.com',
    storageBucket: 'o-nepali.firebasestorage.app',
    androidClientId:
        '259206374027-8s7mtkn4crb15au6177juljdmdt5frma.apps.googleusercontent.com',
    iosClientId:
        '259206374027-vp517itn9fo008tg1d9p2q2id8cmtqjj.apps.googleusercontent.com',
    iosBundleId: 'com.onepali.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe2VDjkze_yEvho31p76j_cbiRgKUIYeg',
    appId: '1:259206374027:web:705d983fba27d07bc76a8e',
    messagingSenderId: '259206374027',
    projectId: 'o-nepali',
    authDomain: 'o-nepali.firebaseapp.com',
    databaseURL: 'https://o-nepali-default-rtdb.firebaseio.com',
    storageBucket: 'o-nepali.firebasestorage.app',
    measurementId: 'G-7E384TBR8W',
  );
}
